# docker-compose.yml
version: '3'
services:
    db:
        image: mariadb:10.2
        ports:
            - 9306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: task_manager

    web:
        build: ./dockerfile/php
        depends_on:
            - db
        ports:
            - 9080:80
        volumes:
            - ./task-manager:/var/www/html
            - ./dockerfile/php/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./dockerfile/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

